feat: implemented discord oauth
UCLA-Creative-Labs/watchdog pull request #13
Opened 2022-01-31 15:51 UTC by BryanPan342

Using discord oauth to see what user is logged in! I think this solution solves a lot of our issues.. Basically this is an easy way for us to see if the person has permissions because we check if they have the `board` role in our discord server.

https://user-images.githubusercontent.com/44623317/151718479-6e975b07-eb14-4cf2-8069-5fff42cfdc21.mov

2022-01-31 17:05 UTC, tylercxu approved these changes
lgtm nice idea

2022-01-31 22:57 UTC, tylercxu requested changes

2022-01-31 22:57 UTC, tylercxu commented on packages/web/website/pages/api/auth/[...nextauth].ts
> +      return !!isBoardMember;
isnt !! repetitive

2022-01-31 23:03 UTC, tylercxu commented on packages/web/website/pages/api/auth/[...nextauth].ts
> +      return !!isBoardMember;
wait nvm it just changes obj to bool

2022-01-31 23:03 UTC, tylercxu approved these changes
lgtm

2022-02-02 00:24 UTC, BryanPan342 commented
@mergifyio refresh

2022-02-02 01:09 UTC, BryanPan342 commented
@Mergifyio refresh

2022-02-02 19:50 UTC, BryanPan342 commented
@mergifyio refresh

2022-02-02 19:52 UTC, merged